title: Mazen Hawwa # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with a background in Information Technology 
  <br><br>
  Deeply inspired by my work with a data analytics company specializing in K12 education, 
  I became a data scientist with the goal of deriving valuable insight from data for the benefit of all.
  
  <br><br>
  <a href="https://www.linkedin.com/in/mazen-hawwa-4823112/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
