title: Mazen Hawwa # your name (or website title) here
#logo: "/images/index.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with a background in Information Technology 
  <br><br>
  Having previously worked for a data analytics company, I was inspired to study Data Science with the goal of deriving valuable insight from data for the benefit of all.
  <br/>
  <br/>
  Equiped with a new set of skills, I am looking to start a data science apprenticeship or junior position that would enable me to develop my career
  in data science.
  <br/>
  <br/>
  Please have a look at some of my practice projects on this portfolio, and keep checking back as I keep adding projects from time to time.
  
  <br><br>
  <a href="https://www.linkedin.com/in/mazen-hawwa-4823112/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
